# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getFunChisqStat <- function(input) {
    .Call('_UniExactFunTest_getFunChisqStat', PACKAGE = 'UniExactFunTest', input)
}

UniEFT <- function(input) {
    .Call('_UniExactFunTest_UniEFT', PACKAGE = 'UniExactFunTest', input)
}

UniEFTC <- function(input) {
    .Call('_UniExactFunTest_UniEFTC', PACKAGE = 'UniExactFunTest', input)
}

